#
# Copyright (c) 2021 Oracle and/or its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

server.port: 8080

vault:
  properties:
    address: "http://localhost:8200"
  k8s:
    address: "${vault.properties.address}"
    # please change this to your k8s cluster address
    # cluster-address: "https://kubernetes.docker.internal:6443"
    cluster-address: "https://10.96.0.1"
    auth:
      k8s:
        enabled: true
        # this role is created in the code, must be the same value
        token-role: my-role
        service-account-token: "${vault.properties.k8s.service-account-token}"
      app-role:
        enabled: false
      token:
        enabled: false
  token:
    token: "myroot"
    address: "${vault.properties.address}"
    auth:
      k8s:
        enabled: false
      app-role:
        enabled: false
      token:
        enabled: true
  approle:
    address: "${vault.properties.address}"
    auth:
      k8s:
        enabled: false
      app-role:
        enabled: true
      token:
        enabled: false