db:
  source: jdbc
  connection:
    # docker run --rm --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=pokemon -e MYSQL_USER=user -e MYSQL_PASSWORD=changeit  mysql:5.7
    url: jdbc:mysql://127.0.0.1:3306/pokemon?useSSL=false
    username: user
    password: changeit
    poolName: mysql
    initializationFailTimeout: -1
    connectionTimeout: 2000
    helidon:
      pool-metrics:
        enabled: true
        # name prefix defaults to "db.pool." - if you have more than one client within a JVM, you may want to distinguish between them
        name-prefix: "hikari."
  services:
    metrics:
      - type: METER
  health-check:
    type: "dml"
    statementName: "ping"
  statements:
    # Ping statement
    ping: "SET @HELIDON_PING=0"
    # Create database schema
    create-types: "CREATE TABLE POKEMONTYPE (id INTEGER NOT NULL PRIMARY KEY, name VARCHAR(64) NOT NULL)"
    create-pokemons: "CREATE TABLE POKEMON (id INTEGER NOT NULL PRIMARY KEY, name VARCHAR(64) NOT NULL, id_type INTEGER NOT NULL REFERENCES POKEMONTYPE(id))"
    # Select all types
    select-all-types: "SELECT * FROM POKEMONTYPE"
    # Select all pokemons
    select-all-pokemons: "SELECT * FROM POKEMON"
    # Select pokemon by id
    select-pokemon-by-id: "SELECT * FROM POKEMON WHERE id = :id"
    # Select pokemon by name
    select-pokemon-by-name: "SELECT * FROM POKEMON WHERE name = ?"
    # Insert records into database
    insert-type: "INSERT INTO POKEMONTYPE VALUES(?, ?)"
    insert-pokemon: "INSERT INTO POKEMON VALUES(?, ?, ?)"
    # Delete pokemon by id
    delete-pokemon-by-id: "DELETE FROM POKEMON WHERE id = :id"