# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Validate Helidon by Example

on:
  push:
    branches: [ "helidon-3.x" ]
  pull_request:
    branches: [ "helidon-3.x" ]

env:
  JAVA_DISTRO: 'temurin'
  JAVA_VERSION: '17'
  HELIDON_EXAMPLES_REPOSITORY: 'senivam/helidon-examples.git'
  HELIDON_EXAMPLES_BUILD_BRANCH: 'dev-3.x'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean install --file pom.xml
    - name: Build Examples vs Helidon
      run: mkdir -p ./examples-repo && cd ./examples-repo 
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
        repository: ${{ env.HELIDON_EXAMPLES_REPOSITORY }}
        ref: ${{ env.HELIDON_EXAMPLES_BUILD_BRANCH }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3.6.0
      with:
        distribution: ${{ env.JAVA_DISTRO }}
        java-version: ${{ env.JAVA_VERSION }}
        cache: maven
    - name: Examples VS Helidon build
      run: mvn -B clean install
